name: flutter_lokalise
version: 0.1.2
description: >
  A tool to download translation files from Lokalise and convert them to .arb files.
homepage: https://github.com/meniga/flutter_lokalise

environment:
  sdk: ">=2.6.0 <3.0.0"

executables:
  flutter_lokalise:

dependencies:
  archive: ">=2.0.0 <3.0.0"
  args: ">=1.5.0 <2.0.0"
  json_annotation: ">=3.0.0 <4.0.0"
  freezed_annotation: ^0.12.0
  http: ">=0.12.0 <1.0.0"
  logging: ">=0.11.0 <1.0.0"
  meta: ">=1.1.0 <2.0.0"
  path: ">=1.5.0 <2.0.0"
  quiver: ">=2.0.0 <3.0.0"
  string_unescape: ">=1.0.0 <2.0.0"
  yaml: ">=2.0.0 <3.0.0"

dev_dependencies:
  build_runner: ^1.10.1
  json_serializable: ^3.4.0
  freezed: ^0.12.1
  matcher: ^0.12.9
  mock_web_server: ^4.1.1
  mockito: ^4.1.1
  pedantic: ^1.9.2
  remove_from_coverage: ^1.0.7
  test: ^1.15.2
  test_coverage: ^0.4.3
