name: flutter_lokalise
version: 1.0.0
description: >
  A tool to download translation files from Lokalise and convert them to .arb files.
homepage: https://github.com/meniga/flutter_lokalise

environment:
  sdk: ">=2.12.0 <3.0.0"

executables:
  flutter_lokalise:

dependencies:
  archive: ^3.3.0
  args: ^2.3.1
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  http: ^0.13.4
  logging: ^1.0.2
  meta: ^1.8.0
  path: ^1.8.1
  quiver: ^3.1.0
  yaml: ^3.1.1

dev_dependencies:
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  matcher: ^0.12.11
  mock_web_server: ^5.0.0-nullsafety.1
  mockito: ^5.2.0
  pedantic: ^1.11.1
  remove_from_coverage: ^2.0.0
  test: ^1.21.1
