name: flutter_lokalise
version: 1.0.0
description: >
  A tool to download translation files from Lokalise and convert them to .arb files.
homepage: https://github.com/meniga/flutter_lokalise

environment:
  sdk: ">=2.12.0 <3.0.0"

executables:
  flutter_lokalise:

dependencies:
  archive: ^3.1.2
  args: ^2.1.0
  json_annotation: ^4.0.1
  freezed_annotation: ^0.14.1
  http: ^0.13.3
  logging: ^1.0.1
  meta: ^1.3.0
  path: ^1.8.0
  quiver: ^3.0.1
  yaml: ^3.1.0

dev_dependencies:
  build_runner: ^2.0.2
  json_serializable: ^4.1.1
  freezed: ^0.14.1
  matcher: ^0.12.10
  mock_web_server: ^5.0.0-nullsafety.1
  mockito: ^5.0.7
  pedantic: ^1.11.0
  remove_from_coverage: ^2.0.0
  test: ^1.17.3
